version: '1.0'

services:
  app:
    image: subfastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3500:3500"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3500", "--reload"]
