# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subfastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subfastapi
  template:
    metadata:
      labels:
        app: subfastapi
    spec:
      containers:
      - name: subfastapi
        image: wjdguswn1203/subfastapi:lastest
        ports:
        - containerPort: 3500
        envFrom:
        - configMapRef:
            name: app-config
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3500", "--reload"]
